name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # flavors-start
        flavor:
          [
            "ci_light",
            "dart",
            "documentation",
            "dotnet",
            "go",
            "java",
            "javascript",
            "php",
            "python",
            "ruby",
            "rust",
            "salesforce",
            "scala",
            "swift",
            "terraform"
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: flavors/${{ matrix.flavor }}/Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
